trigger:

- master
 
pool:

  vmImage: 'MyWindowsAgent'
 
variables:

  nodeVersion: '21.x'
 
steps:
 
# Checkout latest source code

- checkout: self

  clean: true

  fetchDepth: 0
 
# Install Node.js

- task: UseNode@1

  inputs:

    version: '$(nodeVersion)'

  displayName: 'Install Node.js'
 
# Debug repository structure

- script: |

    echo "===== Current Directory ====="

    pwd

    echo ""

    echo "===== Repository Structure ====="

    find .

    echo ""

    echo "===== frontend ====="

    ls -la frontend

    echo ""

    echo "===== frontend/creditscore ====="

    ls -la CreditScoreAngular/credit-score-frontend

  displayName: 'Debug Repository Structure'
 
# Install Angular dependencies

- script: |

    npm install

  workingDirectory: 'CreditScoreAngular/credit-score-frontend'

  displayName: 'Install Angular Packages'
 
# Build Angular

- script: |

    npm run build

  workingDirectory: 'CreditScoreAngular/credit-score-frontend'

  displayName: 'Build Angular'
 
# Publish Angular artifact

- task: PublishBuildArtifacts@1

  inputs:

    PathtoPublish: 'CreditScoreAngular/credit-score-frontend/dist'

    ArtifactName: 'Angular'

    publishLocation: 'Container'

  displayName: 'Publish Angular Artifact'
 
# Build Spring Boot

- task: Maven@4

  inputs:

    mavenPomFile: 'CreditScore/pom.xml'

    goals: 'clean package -DskipTests'

    javaHomeOption: 'JDKVersion'

    jdkVersionOption: '17'

    mavenVersionOption: 'Default'

    publishJUnitResults: false

  displayName: 'Build Spring Boot'
 
# Publish Spring Boot artifact

- task: PublishBuildArtifacts@1

  inputs:

    PathtoPublish: 'CreditScore/target'

    ArtifactName: 'SpringBoot'

    publishLocation: 'Container'

  displayName: 'Publish Spring Boot Artifact'
 